-- Add SendGrid webhook tracking fields to campaign recipients
ALTER TABLE "CampaignRecipients"
ADD COLUMN "delivered" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "opens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "uniqueOpens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "clicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bounces" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "spamReports" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "unsubscribes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastEventAt" TIMESTAMP(3);
